version: "3"

networks:
  nginx_net:
    driver: bridge

services: 
  postgres:
    image: postgres:12
    container_name: pg_solidarize
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_USER: root
    ports:
      - "5432:5432"
    networks:
      - nginx_net

  node:
    build: 
      context: .
      dockerfile: Dockerfile.node
    command: "npm run start"
    environment:
      - NODE_ENV=production
    expose:
      - "5050"
    ports:
      - "5050:5050"
    networks:
      - nginx_net
    depends_on:
      - postgres  # Esta linha garante que o node inicie após o postgres

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx_net

volumes:
  db_data:
