version: "3"

networks:
  nginx_net:
    driver: bridge

services: 
  postgres:
    image: postgres:12
    container_name: pg_solidarize
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_USER: root
    ports:
      - "5432:5432"
    networks:
      - nginx_net

  node:
    build: 
      context: .
      dockerfile: Dockerfile.node
    command: "npm run start"
    environment:
      - NODE_ENV=production
    expose:
      - "5050"
    ports:
      - "5050:5050"
    networks:
      - nginx_net
    depends_on:
      - postgres  

  nginx:
    container_name: nginx
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - nginx_net
    depends_on:
      - postgres 
      - node 

volumes:
  db_data:


# docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t geandersonlemonte/solidarize-docker:latest . --push